### ISSUE TITLE
Make sure if a Supabase Auth user is registered, they should not be allowed to register again

### ISSUE THREAD

**Issue by 5hraddha** [Full-Stack-Collective/connectient#124]
Right now, if a Supabase Auth user registers, there is no check to see if the user already exists with that email in our DB. 
Something that could help - [Managing User Data](https://supabase.com/docs/guides/auth/managing-user-data#accessing-user-metadata)

**Comment by mentalcaries** [comment]
@5hraddha this may not be something we need to deal with. I was working on it this morning and there's no way to check if the user exists. According to Supabase, exposing whether or not an account already exists can be a security issue.
Instead, they have options in place: if a user tries to re-register an account, they will get a password recovery page
https://github.com/supabase/supabase-js/issues/296#issuecomment-976200828

**Comment by 5hraddha** [comment]
@mentalcaries Oh..okay! Did you try the trick mentioned in the article linked above?
