### ISSUE TITLE
Convert Appointment Form to Multi Step form

### ISSUE THREAD

**Issue by mentalcaries** [Full-Stack-Collective/connectient#95]
Right now, the appointment for is just one long form that seems to ask a lot for users.

It would appear less overwhelming to users if the form can be split it up in to 2-3 steps (as a stepper).
Right now Shadcn does not have this component fully implemented, but there are ways to work around it.

Current Shadcn thread for it: https://github.com/shadcn-ui/ui/pull/318

**Comment by 5hraddha** [comment]
I have made a multistep appointment form in my branch - `shraddha/feature/appointment-form`. I was wondering when the Stepper component will finally be available. So, just divided the full appointment form into two parts. Just testing the code and could share once done.
